// Generated by gencpp from file bot_simulator/botpose.msg
// DO NOT EDIT!


#ifndef BOT_SIMULATOR_MESSAGE_BOTPOSE_H
#define BOT_SIMULATOR_MESSAGE_BOTPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bot_simulator
{
template <class ContainerAllocator>
struct botpose_
{
  typedef botpose_<ContainerAllocator> Type;

  botpose_()
    : x(0)
    , y(0)
    , direction()  {
    }
  botpose_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , direction(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::bot_simulator::botpose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bot_simulator::botpose_<ContainerAllocator> const> ConstPtr;

}; // struct botpose_

typedef ::bot_simulator::botpose_<std::allocator<void> > botpose;

typedef boost::shared_ptr< ::bot_simulator::botpose > botposePtr;
typedef boost::shared_ptr< ::bot_simulator::botpose const> botposeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bot_simulator::botpose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bot_simulator::botpose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bot_simulator::botpose_<ContainerAllocator1> & lhs, const ::bot_simulator::botpose_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bot_simulator::botpose_<ContainerAllocator1> & lhs, const ::bot_simulator::botpose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bot_simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bot_simulator::botpose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bot_simulator::botpose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bot_simulator::botpose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bot_simulator::botpose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot_simulator::botpose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot_simulator::botpose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bot_simulator::botpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f292931a9007358d8f0a3620e1cc931";
  }

  static const char* value(const ::bot_simulator::botpose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f292931a9007358ULL;
  static const uint64_t static_value2 = 0xd8f0a3620e1cc931ULL;
};

template<class ContainerAllocator>
struct DataType< ::bot_simulator::botpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bot_simulator/botpose";
  }

  static const char* value(const ::bot_simulator::botpose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bot_simulator::botpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y\n"
"string direction\n"
"\n"
;
  }

  static const char* value(const ::bot_simulator::botpose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bot_simulator::botpose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct botpose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bot_simulator::botpose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bot_simulator::botpose_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOT_SIMULATOR_MESSAGE_BOTPOSE_H
