// Generated by gencpp from file auv_chat/ChatMsg.msg
// DO NOT EDIT!


#ifndef AUV_CHAT_MESSAGE_CHATMSG_H
#define AUV_CHAT_MESSAGE_CHATMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auv_chat
{
template <class ContainerAllocator>
struct ChatMsg_
{
  typedef ChatMsg_<ContainerAllocator> Type;

  ChatMsg_()
    : sender()
    , message()  {
    }
  ChatMsg_(const ContainerAllocator& _alloc)
    : sender(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _sender_type;
  _sender_type sender;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::auv_chat::ChatMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auv_chat::ChatMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ChatMsg_

typedef ::auv_chat::ChatMsg_<std::allocator<void> > ChatMsg;

typedef boost::shared_ptr< ::auv_chat::ChatMsg > ChatMsgPtr;
typedef boost::shared_ptr< ::auv_chat::ChatMsg const> ChatMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auv_chat::ChatMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auv_chat::ChatMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::auv_chat::ChatMsg_<ContainerAllocator1> & lhs, const ::auv_chat::ChatMsg_<ContainerAllocator2> & rhs)
{
  return lhs.sender == rhs.sender &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::auv_chat::ChatMsg_<ContainerAllocator1> & lhs, const ::auv_chat::ChatMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace auv_chat

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::auv_chat::ChatMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_chat::ChatMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_chat::ChatMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_chat::ChatMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_chat::ChatMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_chat::ChatMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auv_chat::ChatMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "985ef42f02a992c58d5de728edeb121e";
  }

  static const char* value(const ::auv_chat::ChatMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x985ef42f02a992c5ULL;
  static const uint64_t static_value2 = 0x8d5de728edeb121eULL;
};

template<class ContainerAllocator>
struct DataType< ::auv_chat::ChatMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auv_chat/ChatMsg";
  }

  static const char* value(const ::auv_chat::ChatMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auv_chat::ChatMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sender\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::auv_chat::ChatMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auv_chat::ChatMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChatMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auv_chat::ChatMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auv_chat::ChatMsg_<ContainerAllocator>& v)
  {
    s << indent << "sender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.sender);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUV_CHAT_MESSAGE_CHATMSG_H
